# build stage
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY public ./public
COPY src ./src
RUN npm run build

# production stage
FROM node:20

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/build ./build

# Define a porta que o Railway deve usar
ENV PORT=8080
EXPOSE 8080

CMD ["sh", "-c", "serve -s build -l $PORT"]