# build stage
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM node:20

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/build ./build

CMD ["sh", "-c", "serve -s build -l $PORT"]